spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_social?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    root: info


oauth:
  kakao:
    client_id: 4cc737590e1b8b3928a19e6e11f0702c
    redirect_uri: http://localhost:3000/oauth/redirected/kakao
    client_secret: UFGuJby4lYnnquZiwDVFrrzezegL81sp
    scope: profile_nickname, profile_image, account_email

  naver:
    client_id: O6M1x2roD_H_hqeu_dHX
    redirect_uri: http://localhost:3000/oauth/redirected/naver
    client_secret: VkSB5sDFVF
    scope:

  google:
    client_id: 433951529221-irud4erpgn9lfll4j9pc61k0f4jogki6.apps.googleusercontent.com
    redirect_uri: http://localhost:3000/oauth/redirected/google
    client_secret: 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
    scope:
      - email
      - profile
